name: hera_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  hera_core:
    path: ../hera_core

  softi_common:
    path: ../../../packages/package_flutter_common
     
  softi_firebase:
    path: ../../../packages/package_flutter_firebase

  softi_mediamanager:
    path: ../../../packages/package_flutter_mediamanager

  softi_form:
    path: ../../../packages/package_flutter_form

  # softi_common:
  #   git:
  #     url: https://github.com/atoumbre/package_flutter_common.git
  #     ref: v0.3.1
  
  # softi_firebase:
  #   git:
  #     url: https://github.com/atoumbre/package_flutter_firebase.git
  #     ref: v0.1.2

  get: ^4.1.2
  flutter_platform_widgets:
  velocity_x: 
  easy_debounce:
  cached_network_image:
  flutter_config: 
  flutter_staggered_grid_view: 
  getwidget:
  flutter_svg: 
  pin_entry_text_field: 
  story_view: 
  firebase_database:
  timeago:
  pedantic:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
  faker:

dependency_overrides:
  intl: ^0.17.0
  extended_image: 1.5.0-dev
  date_range_picker:
    git:
      url: https://github.com/LempereurBenjamin/date_range_picker

flutter:
  uses-material-design: true

  fonts:
    - family: 'ArialBold'
      fonts:   
        - asset: assets/fonts/arialBold.ttf

    - family: 'ArialSemiBold'
      fonts:   
        - asset: assets/fonts/arialSemiBold.TTF

    - family: 'ArialMedium'
      fonts:   
        - asset: assets/fonts/arialMedium.ttf
          
    - family: 'ArialRegular'
      fonts:   
        - asset: assets/fonts/arialRegular.ttf

  
  assets:
    - assets/
    - assets/images/
    - assets/icons/


analyzer:
  exclude:
    - "**/ecommerce/*"
    - "**/temp/*"
    - "**/*.g.dart"
    - "**/*.freezed.dart"