name: hera_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  hera_core:
    path: ../hera_core

  softi_common:
    path: ../../../packages/package_flutter_common
     
  softi_firebase:
    path: ../../../packages/package_flutter_firebase

  softi_mediamanager:
    path: ../../../packages/package_flutter_mediamanager

  # softi_form:
  #   path: ../../../packages/package_flutter_form

  # softi_common:
  #   git:
  #     url: https://github.com/atoumbre/package_flutter_common.git
  #     ref: v0.3.1
  
  # softi_firebase:
  #   git:
  #     url: https://github.com/atoumbre/package_flutter_firebase.git
  #     ref: v0.1.2

  get: ^4.1.3 
  flutter_platform_widgets: ^1.1.0
  velocity_x: ^2.6.1 
  easy_debounce: ^2.0.0
  cached_network_image: ^3.0.0
  flutter_config: 
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3 
  getwidget: ^2.0.1-nullsafety.4
  flutter_svg: ^0.21.0-nullsafety.0 
  pin_entry_text_field: 
  story_view: ^0.13.0-nullsafety.1 
  firebase_database: ^6.1.1
  timeago: ^3.0.2
  pedantic: ^1.11.0
  flutter_datetime_picker:
  datetime_picker_formfield: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  faker: ^2.0.0-rc.2
  

flutter:
  uses-material-design: true

  fonts:
    - family: 'ArialBold'
      fonts:   
        - asset: assets/fonts/arialBold.ttf

    - family: 'ArialSemiBold'
      fonts:   
        - asset: assets/fonts/arialSemiBold.TTF

    - family: 'ArialMedium'
      fonts:   
        - asset: assets/fonts/arialMedium.ttf
          
    - family: 'ArialRegular'
      fonts:   
        - asset: assets/fonts/arialRegular.ttf

  
  assets:
    - assets/
    - assets/images/
    - assets/icons/


analyzer:
  exclude:
    - "**/ecommerce/*"
    - "**/temp/*"
    - "**/*.g.dart"
    - "**/*.freezed.dart"