name: hera_core
description: A new Flutter package project.
version: 0.0.1
author: Atoumbre
homepage: atoumbre.com
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  softi_common:
    path: ../../../packages/package_flutter_common
     
  softi_firebase:
    path: ../../../packages/package_flutter_firebase

  # softi_common:
  #   git:
  #     url: https://github.com/atoumbre/package_flutter_common.git
  #     ref: v0.3.1
  
  # softi_firebase:
  #   git:
  #     url: https://github.com/atoumbre/package_flutter_firebase.git
  #     ref: v0.1.2
  
  cloud_functions: ^1.0.2
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  nested: ^1.0.0
  geocoding: ^2.0.0
  dio: ^4.0.0
  retrofit: ^2.0.0-beta1
  flutter_config: #^1.0.8


# flutter packages pub run build_runner watch --delete-conflicting-outputs
# flutter packages pub run build_runner build --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner:
  json_serializable: ^4.1.0
  retrofit_generator: ^2.0.0-beta3
  freezed: ^0.14.1+2

# dependency_overrides:
#   intl: ^0.17.0
  # extended_image: 1.5.0-dev
  
flutter:

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"